name: apache-beam
on:
  push:
    paths:
      - 'envs/apache-beam.yaml'
      - '.github/workflows/apache-beam.yaml'

jobs:
  create-env:
    name: ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]  # windows not support
        
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: install micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: envs/apache-beam.yaml
          environment-name: apache-beam
          
  simulate-osx-arm64:
    name: simulate-osx-arm64
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        
      - name: install micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-name: mamba
      
      - name: simulate environment creation
        shell: bash -l {0}
        run: |
          micromamba activate mamba
          CONDA_SUBDIR=osx-arm64 mamba create \
            --name apache-beam \
            --dry-run \
            -c conda-forge \
            apache-beam
