name: pub-cvae-mri-asd
on:
  push:
    paths:
      - 'envs/pub-cvae-mri-asd.yaml'
      - '.github/workflows/pub-cvae-mri-asd.full.yaml'

jobs:
  create-env:
    name: ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        
      - name: create environment with mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: defaults
          channel-priority: flexible
          activate-environment: pub-cvae-mri-asd
          environment-file: envs/pub-cvae-mri-asd.full.yaml
      
      - name: check solution
        shell: bash -l {0}
        run: |
          mamba env export
