name: so-igraph
on:
  push:
    paths:
      - 'envs/so-igraph.yaml'
      - '.github/workflows/so-igraph.yaml'

jobs:
  create-env:
    name: ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]  # windows not supported
        
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        
      - name: create environment with mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge
          channel-priority: flexible
          activate-environment: so-igraph
          environment-file: envs/so-igraph.yaml
      
      - name: check solution
        shell: bash -l {0}
        run: |
          mamba env export
      
      - name: test import
        shell: bash -l {0}
        run: |
          R -e "library(igraph)"
