name: vep
on:
  push:
    paths:
      - 'envs/vep.yaml'
      - '.github/workflows/vep.yaml'

jobs:
  create-env:
    name: ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]  # windows not support
        
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        
      - name: create environment with mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge,bioconda,defaults
          channel-priority: flexible
          activate-environment: vep
          environment-file: envs/vep.yaml
      
      - name: test vep
        shell: bash -l {0}
        run: |
          vep --help
